### PR TITLE
[Reviewer: Graeme] Chronos fix up

### LINKED ISSUE #177: TimerHandler::get_timers_for_node not honouring Max_responses
In https://github.com/Metaswitch/chronos/blob/dev/src/main/timer_handler.cpp#L440   the get_timers_for_node function (L349) creates the counter retrieved_timers to compare to the max_responses value passed in. 
However, at no point in the function does it increment retrieved_timers, and so it will only break out of the for loop when it reaches the end of the timer store, rather than after the appropriate number of iterations as defined by max_responses. 
The function would also duplicate its debug trace if exiting the loop through the max_responses comparison. The debug text needs to be altered to specify which method exited the for loop, or at least show some differentiation between the two.

### LINKED ISSUE #189: Chronos code coverage is below standard
Seen in CI:

```
Error: some files unexpectedly have less than 100% code coverage:
modules/cpp-common/src/timer_counter.cpp
src/main/chronos_internal_connection.cpp
src/main/http_callback.cpp
src/main/timer.cpp
src/main/timer_handler.cpp
src/main/timer_store.cpp
Marking build unstable.
```

### PR DESCRIPTION
**Pull request by eleanor-merry**
Graeme, can you please review these changes to sort out the TODOs in the Chronos code and fix up the coverage?

Fixes #189 and fixes #177

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -127,12 +127,22 @@ ${BUILD_DIR}/usr/include/chronos_alarmdefinition.h : ${BUILD_DIR}/bin/chronos_al
...
 valgrind_xml: ${OBJ_DIR_TEST}/chronos.memcheck
+	@xmllint --xpath '//error/kind' ${OBJ_DIR_TEST}/chronos.memcheck 2>&1 | \
+		sed -e 's#<kind>##g' | \
+                sed -e 's#</kind>#\n#g' | \
+                sort > $(VG_LIST)
+	@if grep -q -v "XPath set is empty" $(VG_LIST) ; then \
+                echo "Error: some memory errors have been detected" ; \
+                cat $(VG_LIST) ; \
+                echo "See ${OBJ_DIR_TEST}/chronos.memcheck for further details." ; \
+	fi
```
Comment (graemerobertson) [inline Makefile]: As discussed, this is all a complete mystery to me so if you're at all concerned about it, ask someone else to look over it. It sounds like you're not, which is fine by me.

File: src/test/test_globals.cpp [hunk 2]
```diff
@@ -0,0 +1,151 @@
...
+
+#include "globals.h"
+#include "test_interposer.hpp"
+#include <gtest/gtest.h>
+#include <gmock/gmock.h>
+#include <map>
+
+/*****************************************************************************/
+/* Test fixture                                                              */
+/*****************************************************************************/
```
Comment (graemerobertson) [inline src/test/test_globals.cpp]: This comment is in a fairly random place (and also fairly pointless).

File: src/main/timer_handler.cpp [hunk 3]
```diff
@@ -104,93 +106,96 @@ TimerHandler::~TimerHandler()
...
-      else if (Utils::overflow_less_than(timer->start_time_mono_ms,
-                               existing_tp.active_timer->start_time_mono_ms))
+    if ((timer->is_matching_cluster_view_id(cluster_view_id)) &&
+        !(existing_tp.active_timer->is_matching_cluster_view_id(cluster_view_id)))
+    {
+      // If the new timer matches the current cluster view ID, and the old timer
+      // doesn't, always prioritise the new timer.
+      TRC_DEBUG("Adding timer with current cluster view ID");
+    }
+    else if (timer->sequence_number == existing_tp.active_timer->sequence_number)
```
Comment (graemerobertson) [inline src/main/timer_handler.cpp]: Lines 132-156 and 157-183 are identical. We could remove this duplication by making this if statement (considerably) bigger (i.e. if sequence numbers are the same and the timer is newer or sequence numbers are different and timer is more recent then add the timer; otherwise don't add the timer).

Alternatively (or possibly as well), the TRC_DEBUG logs could at least identify the slightly different scenarios here - you seem to have explicitly changed them to be identical, although it's difficult to figure out exactly what changes you've made here and what has just been moved!

File: src/main/timer_handler.cpp [hunk 4]
```diff
@@ -104,93 +106,96 @@ TimerHandler::~TimerHandler()
...
     }
     else
     {
-      // One of the sequence number is non-zero - at least one request is not
+      // One of the sequence numbers is non-zero - at least one request is not
       // from the client
-      if (near_time(timer->start_time_mono_ms, existing_tp.active_timer->start_time_mono_ms) &&
-          (timer->sequence_number < existing_tp.active_timer->sequence_number)               &&
+      if ((near_time(timer->start_time_mono_ms, existing_tp.active_timer->start_time_mono_ms)) &&
+          (timer->sequence_number < existing_tp.active_timer->sequence_number)                 &&
```
Comment (graemerobertson) [inline src/main/timer_handler.cpp]: Not a fan of this

File: src/main/timer_handler.cpp [hunk 5]
```diff
@@ -204,32 +209,28 @@ void TimerHandler::add_timer(Timer* timer, bool update_stats)
           TRC_WARNING("Deleting out of date timer from timer map");
         }
 
-        new_tp.information_timer = existing_tp.active_timer; // TODO update the replica tracker
-        existing_tp.active_timer = NULL;
-        update_stats = false;
+        delete new_tp.information_timer;
```
Comment (graemerobertson) [inline src/main/timer_handler.cpp]: new_tp.information_timer can't be set to anything at this point, right? So I don't think we should delete it here, (and ~7 lines below).

File: src/main/timer_handler.cpp [hunk 6]
```diff
@@ -550,23 +558,27 @@ void TimerHandler::run() {
     {
       struct timespec next_pop;
       clock_gettime(CLOCK_MONOTONIC, &next_pop);
-// TODO Add explanatory comment
```
Comment (graemerobertson) [inline src/main/timer_handler.cpp]: I appreciate that we've managed to lose the magic numbers, but this code could probably still do with an explanatory comment IMO - I'm not sure what's going

File: src/test/test_timer_store.cpp [hunk 7]
```diff
@@ -855,58 +881,3 @@ TYPED_TEST(TestTimerStore, SelectTimersTakeInformationalTimers)
                          TestFixture::timers[2]->interval_ms + TIMER_GRANULARITY_MS);
   TestFixture::ts->fetch_next_timers(next_timers);
 }
-
-/*TYPED_TEST(TestTimerStore, ModifySavedTimers)
```
Comment (graemerobertson) [inline src/test/test_timer_store.cpp]: Why is this test no longer a thing?

**Comment by graemerobertson** [comment]
I've reviewed. Looks pretty handy. Can you let me know when you've merged?

Some comments inline, two thrilling comments on test_timer_handler.cpp here.
* I don't like _th as a name for anything but whatever.
* All the WillOnce etc lines are indented inconsistently, and none of them are indented as I would have indented them.

Ta.
Graeme

File: src/test/test_timer_store.cpp (hunk 7 above)
Comment (eleanor-merry) [inline src/test/test_timer_store.cpp]: The function has moved to the timer handler (and is tested in test_timer_handler)
