### PR TITLE
[Reviewer: Ellie] More helpful error message if unable to parse config file

### LINKED ISSUE #266: Chronos does not provide adequate diags for invalid config file
#### Symptoms

Using a chronos.conf containing the following:

```
[http]
bind-address = $(hostname -I)
bind-port = 7253
threads = 50
```

Chronos fails to start, and prints no logs. Looking at a core dump, we see the following backtrace:

```
#0  0x00007febb7a8ccc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007febb7a900d8 in __GI_abort () at abort.c:89
#2  0x000000000047b196 in signal_handler (sig=6) at main.cpp:173
#3  <signal handler called>
#4  0x00007febb7a8ccc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#5  0x00007febb7a900d8 in __GI_abort () at abort.c:89
#6  0x00007febb8181535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007febb817f6d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007febb817f703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007febb817f976 in __cxa_rethrow () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007febb9957f21 in boost::program_options::store(boost::program_options::basic_parsed_options<char> const&, boost::program_options::variables_map&, bool) () from /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.54.0
#11 0x00000000004346b9 in Globals::update_config (this=this@entry=0x1888f70) at globals.cpp:118
#12 0x000000000043414d in operator() (__p=0x1888f70, this=<synthetic pointer>) at /usr/include/c++/4.8/bits/stl_function.h:551
#13 Updater (run_on_start=true, signal_waiter=<optimized out>, myFunctor=..., pointer=0x1888f70, this=0x188bc00)
    at ../modules/cpp-common/include/updater.h:61
#14 Globals::Globals (this=0x1888f70, config_file=..., cluster_config_file=...) at globals.cpp:85
#15 0x0000000000419140 in main (argc=<optimized out>, argv=0x7ffe78157288) at main.cpp:202
```

It looks like we've hit an exception trying to parse the config file, failed to catch it, and that the behavior for uncaught exceptions does not include saving off the details of what went wrong.

The solution for this case is to catch the exception, print an error message, and exit with a failure return code. More generally, we should look at whether our uncaught exception handling is up to scratch.
#### Impact

This makes it hard for users to debug the case when their configuration is badly formed.
#### Release and environment

Seen on release 96.

### PR DESCRIPTION
**Pull request by sebrexmetaswitch**
If we hit an exception trying to parse on of the config files, catch it and try to log a helpful error message to make it easier to diagnose what went wrong, then exit.

(If the problem was with logging config, we can't write a log)

Fixes #266 

Testing done:
- verified the live tests still pass 
- verified we get a helpful log message if there's a problem. The ouput we see is like:
> 24-11-2016 12:51:43.631 UTC Error globals.cpp:155: Error parsing config file: /etc/chronos/chronos.conf
> 24-11-2016 12:51:43.631 UTC Error globals.cpp:156: the argument ('7253A') for option 'port' is invalid

---
This change is [Reviewable](https://reviewable.io/reviews/metaswitch/chronos/322)

### CODE REVIEW

File: src/globals.cpp [hunk 1]
```diff
@@ -126,13 +140,24 @@ void Globals::update_config()
...
 
-  // Set up the per node configuration. Set up logging early so we can 
+  // Set up the per node configuration. Set up logging early so we can
   // log the other settings
 #ifndef UNIT_TEST
   Log::setLogger(new Logger(conf_map["logging.folder"].as<std::string>(), "chronos"));
   Log::setLoggingLevel(conf_map["logging.level"].as<int>());
 #endif
 
+  // We do error checking after trying to set up the logger, so that we have
```
Comment (eleanor-merry) [inline src/globals.cpp]: I'm not sure about waiting until we've got logging setup - I think you should exit when you catch the exception, and fprintf to stderr the error message (e.g. https://github.com/Metaswitch/sprout/blob/dev/src/main.cpp#L501)

File: src/globals.cpp [hunk 2]
```diff
@@ -126,13 +140,24 @@ void Globals::update_config()
...
+  // somewhere to log the error.
+  if (error != "")
+  {
+    // LCOV_EXCL_START
+    TRC_ERROR("Error parsing config file: %s", error_config_file.c_str());
```
Comment (eleanor-merry) [inline src/globals.cpp]: These should be in the same TRC statement

**Comment by sebrexmetaswitch** [comment]
As discussed, I've changed this to print to sterr, but that's currently not going anywhere useful because of issue #278
