### PR TITLE
[Reviewer: Ellie] Move to working timer heap

### LINKED ISSUE #257: Setting timers for >1 hour causes log spam
#### Symptoms

Each timer set for more than an hour in the future causes the following log:

`21-04-2016 16:38:44.839 UTC Warning timer_store.cpp:148: Adding timer to extra heap, consider re-building with a larger LONG_WHEEL_NUM_BUCKETS constant`

#### Impact

Tens of thousands of these logs can be written out at high load, causing high disk usage, high disk IO, and potentially blocked threads waiting for disk IO.

#### Release and environment 

All Chronos releases to date.

#### Steps to reproduce

Register with a SIP client configured with a 2-hour registration interval.

### PR DESCRIPTION
**Pull request by rkd-msw**
This switches to the timer heap from https://github.com/Metaswitch/cpp-common/pull/517, which fixes #257, #258 and #259.

One question I'd particularly like your view on: I've made the heap store a `Timer*` (the active timer) rather than a TimerPair. is this right? I didn't quite understand the connection between active and information timers - I think if a timer's in the store it's always an active timer, and information timers are just how we track timers that have been resynced away, but I wasn't sure.

(I previously also asked "I hit a UT issue relating to overflow, where I had timers for 1 hour, 5 hours and 10 hours and the 5-hour one popped first in the Overflow2h case. I fixed this by using a 3-hour timer rather than a 1-hour one. I think this is working as designed - I think any timers below 2h overflow and appear very large - but wanted a second opinion." @bossmc pointed out that this was definitely wrong, and I needed to make the heap overflow-aware.)

### CODE REVIEW

File: include/timer_store.h [hunk 1]
```diff
@@ -134,6 +135,9 @@ class TimerStore
   // Fetch the next buckets of timers to pop and remove from store
   virtual void fetch_next_timers(std::unordered_set<TimerPair>& set);
 
+  // Removes all timers from the wheels and heap, without deleting them. Useful for cleanup in UT.
```
Comment (eleanor-merry) [inline include/timer_store.h]: Line length

File: src/timer.cpp [hunk 2]
```diff
@@ -97,13 +97,13 @@ Timer::~Timer()
...
 // Returns the next pop time in ms.
-uint32_t Timer::next_pop_time()
+uint32_t Timer::next_pop_time() const
 {
   std::string localhost;
   int replica_index = 0;
   __globals->get_cluster_local_ip(localhost);
 
-  for (std::vector<std::string>::iterator it = replicas.begin();
+  for (std::vector<std::string>::const_iterator it = replicas.begin();
```
Comment (eleanor-merry) [inline src/timer.cpp]: Alignment

File: src/timer_store.cpp [hunk 3]
```diff
@@ -70,18 +70,8 @@ TimerStore::TimerStore(HealthChecker* hc) :
   _tick_timestamp = to_short_wheel_resolution(timestamp_ms());
 }
 
-TimerStore::~TimerStore()
+void TimerStore::clear()
```
Comment (eleanor-merry) [inline src/timer_store.cpp]: I don't understand why this has been split out?

File: src/ut/test_timer_store.cpp [hunk 4]
```diff
@@ -154,6 +154,8 @@ class TestTimerStore : public Base
     delete timers[2]; timers[2] = NULL;
     delete tombstone; tombstone = NULL;
 
+    // Clearing the timer store before deleting it prevents double-deletion of timers
+    ts->clear();
```
Comment (eleanor-merry) [inline src/ut/test_timer_store.cpp]: But you call clear in the destructor

File: src/ut/test_timer_store.cpp [hunk 5]
```diff
@@ -381,6 +383,38 @@ TYPED_TEST(TestTimerStore, MultiLongGetTimersTest)
...
+  TestFixture::timers[2]->interval_ms = (3600 * 1000 * 5) + (TIMER_GRANULARITY_MS * 6);
+
+  TestFixture::ts_insert_helper(TestFixture::timers[0]);
+  TestFixture::ts_insert_helper(TestFixture::timers[1]);
+  TestFixture::ts_insert_helper(TestFixture::timers[2]);
+
+  // Advance time to when the timer with ID 2 should pop, and ask for the next
+  // timer to pop. We should get one and it should be the timer with ID 2.
+
+  cwtest_advance_time_ms(TestFixture::timers[1]->interval_ms + TIMER_GRANULARITY_MS);
```
Comment (eleanor-merry) [inline src/ut/test_timer_store.cpp]: You're using timer 1 here, not 2

File: src/timer_store.cpp [hunk 6]
```diff
@@ -382,16 +388,9 @@ void TimerStore::remove_timer_from_timer_wheel(TimerPair timer)
...
-        heap_it = std::find(_extra_heap.begin(), _extra_heap.end(), timer);
-
-        if (heap_it != _extra_heap.end())
-        {
-          // Timer is in heap, remove it.
-          _extra_heap.erase(heap_it, heap_it + 1);
-          std::make_heap(_extra_heap.begin(), _extra_heap.end());
-        }
-        else
+        bool success = _extra_heap.remove(timer.active_timer);
```
Comment (eleanor-merry) [inline src/timer_store.cpp]: I think there should be a UT somewhere where you try to remove a non-existent timer from the heap

File: src/timer_store.cpp [hunk 7]
```diff
@@ -306,39 +309,42 @@ void TimerStore::maybe_refill_wheels()
   }
 }
 
+TimerPair TimerStore::pop_from_heap()
```
Comment (eleanor-merry) [inline src/timer_store.cpp]: This doesn't actually pop anything from the heap - can this be renamed?

**Comment by eleanor-merry** [comment]
Looks good, some comments

File: src/ut/test_timer_store.cpp (hunk 4 above)
Comment (rkd-msw) [inline src/ut/test_timer_store.cpp]: I call `clear` in the destructor *after* iterating over `_timer_lookup_id_table` and deleting the timers. This line ensures that `_timer_lookup_id_table` is empty before the destructor runs and it doesn't delete timers.

File: src/timer_store.cpp (hunk 3 above)
Comment (rkd-msw) [inline src/timer_store.cpp]: See https://github.com/Metaswitch/chronos/pull/267#discussion_r66148968

File: src/ut/test_timer_store.cpp (hunk 5 above)
Comment (rkd-msw) [inline src/ut/test_timer_store.cpp]: The timers are indexed as [0], [1], [2] but have timer IDs 1, 2 3. It's a little confusing (but existing test function) so I've been careful to "timer with ID 2" rather than the ambiguous "timer 2".

File: src/timer_store.cpp (hunk 7 above)
Comment (rkd-msw) [inline src/timer_store.cpp]: It's now `get_top_of_heap()`.

File: src/timer_store.cpp (hunk 6 above)
Comment (rkd-msw) [inline src/timer_store.cpp]: Added ("TestTimerStore.RemoveNonexistentTimer")
